"""Cluster detector — find concept clusters in the link graph via connected components."""

from __future__ import annotations

import json
from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

from oar.core.frontmatter import FrontmatterManager
from oar.core.link_graph import LinkGraph
from oar.core.link_resolver import LinkResolver
from oar.core.slug import slugify
from oar.core.vault import Vault
from oar.core.vault_ops import VaultOps

if TYPE_CHECKING:
    from oar.llm.router import LLMRouter


@dataclass
class ConceptCluster:
    """A cluster of closely connected articles."""

    name: str
    slug: str
    article_ids: list[str]
    central_article: str  # Most connected article
    description: str = ""


class ClusterDetector:
    """Detect concept clusters in the link graph."""

    def __init__(
        self,
        vault: Vault,
        ops: VaultOps,
        resolver: LinkResolver,
        router: LLMRouter | None = None,
    ) -> None:
        self.vault = vault
        self.ops = ops
        self.resolver = resolver
        self.router = router
        self.fm = FrontmatterManager()

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    def detect_clusters(
        self, min_size: int = 3, max_size: int = 20
    ) -> list[ConceptCluster]:
        """Find clusters of closely connected articles.

        Simple algorithm:
        1. Build link graph
        2. Find connected components via BFS
        3. Split oversized components by tag similarity
        4. Components with >= min_size articles become clusters
        5. Central article = one with most backlinks in cluster
        """
        graph = self.resolver.build_graph()
        all_nodes = graph.get_all_nodes()

        visited: set[str] = set()
        clusters: list[ConceptCluster] = []

        for node in sorted(all_nodes):
            if node in visited:
                continue

            # BFS to find the connected component.
            component = self._bfs_component(graph, node)
            visited |= component

            if len(component) < min_size:
                continue

            # Split oversized components by tag similarity.
            sub_components = self._split_oversized(component, max_size, min_size)

            for sub in sub_components:
                if len(sub) < min_size:
                    continue

                central = self._find_central(graph, sub)

                name = central.replace("-", " ").title()
                slug = slugify(central)

                clusters.append(
                    ConceptCluster(
                        name=name,
                        slug=slug,
                        article_ids=sorted(sub),
                        central_article=central,
                    )
                )

        return clusters

    # ------------------------------------------------------------------
    # Page generation
    # ------------------------------------------------------------------

    def build_cluster_page(self, cluster: ConceptCluster) -> Path:
        """Generate a cluster page at 03-indices/clusters/cluster-{slug}.md."""
        cluster_dir = self.vault.indices_dir / "clusters"
        cluster_dir.mkdir(parents=True, exist_ok=True)
        path = cluster_dir / f"cluster-{cluster.slug}.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": f"cluster-{cluster.slug}",
            "title": cluster.name,
            "type": "cluster",
            "article_count": len(cluster.article_ids),
            "central_article": cluster.central_article,
            "created": now,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            f"# {cluster.name}\n",
        ]
        if cluster.description:
            body_parts.append(f"\n{cluster.description}\n")
        body_parts.append(
            f"> Concept cluster with **{len(cluster.article_ids)}** articles "
            f"(central: [[{cluster.central_article}]]).\n",
        )
        body_parts.append("## Articles\n")
        for aid in sorted(cluster.article_ids):
            body_parts.append(f"- [[{aid}]]")

        body_parts.append(
            f"\n---\n*Auto-generated by OAR Cluster Detector • "
            f"{len(cluster.article_ids)} articles*\n"
        )

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return path

    def detect_and_build(self, min_size: int = 3, max_size: int = 20) -> list[Path]:
        """Detect clusters and build pages. Returns list of created paths."""
        clusters = self.detect_clusters(min_size=min_size, max_size=max_size)
        paths: list[Path] = []
        for cluster in clusters:
            self.name_cluster(cluster)
            path = self.build_cluster_page(cluster)
            paths.append(path)
        return paths

    # ------------------------------------------------------------------
    # LLM naming
    # ------------------------------------------------------------------

    def name_cluster(self, cluster: ConceptCluster) -> None:
        """Use LLM to name and describe a cluster. Falls back to central article name."""
        if self.router is None:
            return  # Keep the default name from central article

        # Gather article titles for context.
        titles = []
        for aid in cluster.article_ids:
            path = self.ops.get_article_by_id(aid)
            if path:
                meta, _ = self.fm.read(path)
                titles.append(meta.get("title", aid))

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a knowledge management assistant. Given a list of "
                    "article titles that form a concept cluster, provide:\n"
                    "1. A concise cluster name (2-4 words)\n"
                    "2. A one-sentence description of what unites these articles\n\n"
                    'Respond as JSON: {"name": "...", "description": "..."}'
                ),
            },
            {
                "role": "user",
                "content": f"Articles: {json.dumps(titles)}",
            },
        ]

        try:
            response = self.router.complete(messages, task="cluster-name")
            data = json.loads(response.content.strip())
            if "name" in data:
                cluster.name = data["name"]
                cluster.slug = slugify(data["name"])
            if "description" in data:
                cluster.description = data["description"]
        except (json.JSONDecodeError, Exception):
            pass  # Keep default name

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _bfs_component(graph: LinkGraph, start: str) -> set[str]:
        """BFS to find all articles connected to *start*."""
        visited: set[str] = {start}
        queue: deque[str] = deque([start])
        while queue:
            current = queue.popleft()
            neighbours = set(graph.get_forward_links(current)) | set(
                graph.get_backlinks(current)
            )
            for neighbour in neighbours:
                if neighbour not in visited:
                    visited.add(neighbour)
                    queue.append(neighbour)
        return visited

    @staticmethod
    def _find_central(graph: LinkGraph, component: set[str]) -> str:
        """Find the article with the most backlinks within the component."""
        best_node = ""
        best_count = -1
        for node in component:
            backlinks = graph.get_backlinks(node)
            # Only count backlinks from within this component.
            count = sum(1 for bl in backlinks if bl in component)
            if count > best_count:
                best_count = count
                best_node = node
        return best_node

    def _split_oversized(
        self, component: set[str], max_size: int, min_size: int
    ) -> list[set[str]]:
        """Split an oversized component into smaller groups by tag similarity."""
        if len(component) <= max_size:
            return [component]

        # Group articles by shared tags.
        tag_groups: dict[str, set[str]] = {}
        for aid in component:
            path = self.ops.get_article_by_id(aid)
            if not path:
                continue
            meta, _ = self.fm.read(path)
            for tag in meta.get("tags", []):
                tag_groups.setdefault(tag, set()).add(aid)

        # Sort tags by group size (prefer medium-sized groups).
        sorted_tags = sorted(
            tag_groups.keys(),
            key=lambda t: len(tag_groups[t]),
            reverse=True,
        )

        # Greedily assign articles to tag-based groups.
        assigned: set[str] = set()
        sub_groups: list[set[str]] = []
        threshold = max(min_size, len(component) // 3)
        for tag in sorted_tags:
            group = tag_groups[tag] - assigned
            if len(group) >= 2:
                sub_groups.append(group)
                assigned |= group
                if len(sub_groups) >= len(component) // max_size + 1:
                    break

        # Catch any unassigned articles.
        unassigned = component - assigned
        if unassigned:
            sub_groups.append(unassigned)

        return sub_groups if sub_groups else [component]
