"""Map of Content builder — generate topic gateway pages listing related articles."""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from oar.core.frontmatter import FrontmatterManager
from oar.core.slug import slugify
from oar.core.vault import Vault
from oar.core.vault_ops import VaultOps


class MocBuilder:
    """Generate Maps of Content — topic gateway pages listing related articles."""

    def __init__(self, vault: Vault, ops: VaultOps) -> None:
        self.vault = vault
        self.ops = ops
        self.fm = FrontmatterManager()

    def build_moc(self, title: str, domain: str, article_ids: list[str]) -> Path:
        """Generate a MOC page listing articles for a topic area.

        Creates a markdown file at 03-indices/moc/moc-{slug}.md with:
        - YAML frontmatter (type: moc, domain, article_count)
        - Title and description
        - Article listing with [[links]]
        - Footer with stats
        """
        slug = slugify(title)
        moc_dir = self.vault.indices_dir / "moc"
        moc_dir.mkdir(parents=True, exist_ok=True)
        path = moc_dir / f"moc-{slug}.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": f"moc-{slug}",
            "title": title,
            "type": "moc",
            "domain": domain,
            "article_count": len(article_ids),
            "created": now,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            f"# {title}\n",
            f"> Map of Content for the **{domain}** domain "
            f"({len(article_ids)} article{'s' if len(article_ids) != 1 else ''}).\n",
            "## Articles\n",
        ]
        for aid in sorted(article_ids):
            body_parts.append(f"- [[{aid}]]")

        body_parts.append("")
        body_parts.append(
            f"---\n*Auto-generated by OAR Index Builder • "
            f"{len(article_ids)} articles*\n"
        )

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return path

    def build_master_index(self, mocs: list[dict]) -> Path:
        """Generate the _master-index.md — the LLM's entry point for context building.

        Creates 03-indices/_master-index.md with:
        - Table of all MOCs with article counts and one-line summaries
        - Quick stats section
        - Recently updated section
        """
        indices_dir = self.vault.indices_dir
        indices_dir.mkdir(parents=True, exist_ok=True)
        path = indices_dir / "_master-index.md"

        now = datetime.now(timezone.utc).isoformat()
        total_articles = sum(m.get("article_count", 0) for m in mocs)

        metadata = {
            "id": "master-index",
            "title": "Master Index",
            "type": "master-index",
            "moc_count": len(mocs),
            "total_articles": total_articles,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            "# Master Index\n",
            "> Auto-generated entry point for LLM context building.\n",
            "## Maps of Content\n",
        ]

        if mocs:
            body_parts.append("| MOC | Domain | Articles |")
            body_parts.append("|---|---|---|")
            for moc in sorted(mocs, key=lambda m: m.get("title", "")):
                title = moc.get("title", "Untitled")
                domain = moc.get("domain", "")
                count = moc.get("article_count", 0)
                body_parts.append(
                    f"| [[moc-{slugify(title)}\\|{title}]] | {domain} | {count} |"
                )
            body_parts.append("")
        else:
            body_parts.append("*No MOCs generated yet.*\n")

        # Quick stats section.
        body_parts.append("## Quick Stats\n")
        body_parts.append(f"- **MOCs**: {len(mocs)}")
        body_parts.append(f"- **Total articles covered**: {total_articles}")

        # Recently updated section.
        compiled = self.ops.list_compiled_articles()
        recent: list[tuple[str, str]] = []
        for art_path in compiled:
            meta, _ = self.ops.read_article(art_path)
            aid = meta.get("id", art_path.stem)
            updated = meta.get("updated", meta.get("created", ""))
            if updated:
                recent.append((aid, updated))
        recent.sort(key=lambda x: x[1], reverse=True)

        body_parts.append("\n## Recently Updated\n")
        for aid, ts in recent[:20]:
            body_parts.append(f"- [[{aid}]] ({ts[:10]})")

        body_parts.append(
            f"\n---\n*Auto-generated by OAR Index Builder • {len(mocs)} MOCs*\n"
        )

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return path

    def auto_generate_mocs(self) -> list[Path]:
        """Auto-detect topic clusters and generate MOCs.

        Strategy:
        1. Collect all compiled articles with their domain tags
        2. Group by domain
        3. Create one MOC per domain (if >= 2 articles)
        """
        # Group articles by domain.
        domain_articles: dict[str, list[str]] = defaultdict(list)
        for path in self.ops.list_compiled_articles():
            meta, _ = self.ops.read_article(path)
            article_id = meta.get("id")
            if not article_id:
                continue
            domains = meta.get("domain", [])
            if isinstance(domains, str):
                domains = [domains]
            if not domains:
                domains = ["uncategorized"]
            for domain in domains:
                domain_articles[domain].append(article_id)

        created: list[Path] = []
        for domain, articles in sorted(domain_articles.items()):
            if len(articles) < 1:
                continue
            title = domain.replace("-", " ").replace("_", " ").title()
            path = self.build_moc(title, domain, articles)
            created.append(path)
        return created

    def list_mocs(self) -> list[dict]:
        """List all existing MOCs with their metadata.

        Returns list of dicts: {id, title, article_count, domain}
        """
        moc_dir = self.vault.indices_dir / "moc"
        if not moc_dir.is_dir():
            return []
        results: list[dict] = []
        for path in sorted(moc_dir.iterdir()):
            if not path.is_file() or path.suffix != ".md" or path.name == "_index.md":
                continue
            if not path.name.startswith("moc-"):
                continue
            meta, _ = self.fm.read(path)
            results.append(
                {
                    "id": meta.get("id", path.stem),
                    "title": meta.get("title", path.stem),
                    "article_count": meta.get("article_count", 0),
                    "domain": meta.get("domain", ""),
                }
            )
        return results
