"""Orphan and stub tracker — find under-linked and under-developed articles."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from oar.core.frontmatter import FrontmatterManager
from oar.core.link_resolver import LinkResolver
from oar.core.vault import Vault
from oar.core.vault_ops import VaultOps


class OrphanTracker:
    """Track and report orphan articles and stubs."""

    def __init__(self, vault: Vault, ops: VaultOps, resolver: LinkResolver) -> None:
        self.vault = vault
        self.ops = ops
        self.resolver = resolver
        self.fm = FrontmatterManager()

    def write_orphans_page(self, min_backlinks: int = 2) -> list[str]:
        """Generate 03-indices/orphans.md listing articles with few backlinks.

        Returns list of orphan article IDs.
        """
        graph = self.resolver.build_graph()
        orphans = self.resolver.find_orphans(graph, min_backlinks=min_backlinks)

        indices_dir = self.vault.indices_dir
        indices_dir.mkdir(parents=True, exist_ok=True)
        path = indices_dir / "orphans.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": "orphans-index",
            "title": "Orphan Articles",
            "type": "orphan-index",
            "orphan_count": len(orphans),
            "min_backlinks": min_backlinks,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            "# Orphan Articles\n",
            f"> Articles with fewer than **{min_backlinks}** backlinks "
            f"({len(orphans)} found).\n",
        ]
        if orphans:
            body_parts.append("## Articles\n")
            for aid in sorted(orphans):
                backlinks = graph.get_backlink_count(aid)
                body_parts.append(
                    f"- [[{aid}]] ({backlinks} backlink{'s' if backlinks != 1 else ''})"
                )
        else:
            body_parts.append(
                "*No orphan articles found — all articles are well-connected.*"
            )

        body_parts.append(f"\n---\n*Auto-generated by OAR Index Builder*\n")

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return orphans

    def write_stubs_page(self, min_words: int = 200) -> list[str]:
        """Generate 03-indices/stubs.md listing articles with low word count.

        Returns list of stub article IDs.
        """
        stubs: list[str] = []
        for art_path in self.ops.list_compiled_articles():
            meta, body = self.ops.read_article(art_path)
            article_id = meta.get("id")
            if not article_id:
                continue
            wc = self.ops.compute_word_count(body)
            if wc < min_words:
                stubs.append(article_id)

        indices_dir = self.vault.indices_dir
        indices_dir.mkdir(parents=True, exist_ok=True)
        path = indices_dir / "stubs.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": "stubs-index",
            "title": "Stub Articles",
            "type": "stub-index",
            "stub_count": len(stubs),
            "min_words": min_words,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            "# Stub Articles\n",
            f"> Articles with fewer than **{min_words}** words ({len(stubs)} found).\n",
        ]
        if stubs:
            body_parts.append("## Articles\n")
            for aid in sorted(stubs):
                body_parts.append(f"- [[{aid}]]")
        else:
            body_parts.append(
                "*No stub articles found — all articles have sufficient content.*"
            )

        body_parts.append(f"\n---\n*Auto-generated by OAR Index Builder*\n")

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return stubs

    def write_recent_page(self, limit: int = 20) -> Path:
        """Generate 03-indices/recent.md listing recently updated articles."""
        recent: list[tuple[str, str]] = []
        for art_path in self.ops.list_compiled_articles():
            meta, _ = self.ops.read_article(art_path)
            article_id = meta.get("id")
            if not article_id:
                continue
            updated = meta.get("updated", meta.get("created", ""))
            if updated:
                recent.append((article_id, updated))

        recent.sort(key=lambda x: x[1], reverse=True)
        recent = recent[:limit]

        indices_dir = self.vault.indices_dir
        indices_dir.mkdir(parents=True, exist_ok=True)
        path = indices_dir / "recent.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": "recent-index",
            "title": "Recently Updated",
            "type": "recent-index",
            "article_count": len(recent),
            "limit": limit,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            "# Recently Updated\n",
            f"> {len(recent)} most recently updated articles.\n",
            "## Articles\n",
        ]
        for aid, ts in recent:
            body_parts.append(f"- [[{aid}]] ({ts[:10]})")

        if not recent:
            body_parts.append("*No compiled articles found yet.*")

        body_parts.append(f"\n---\n*Auto-generated by OAR Index Builder*\n")

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return path
