"""Tag page builder — generate tag aggregation pages listing articles with each tag."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from oar.core.frontmatter import FrontmatterManager
from oar.core.slug import slugify
from oar.core.vault import Vault
from oar.core.vault_ops import VaultOps


class TagBuilder:
    """Generate tag aggregation pages listing articles with each tag."""

    def __init__(self, vault: Vault, ops: VaultOps) -> None:
        self.vault = vault
        self.ops = ops
        self.fm = FrontmatterManager()

    def build_tag_page(self, tag: str, article_ids: list[str]) -> Path:
        """Generate a tag page at 03-indices/tags/tag-{tag}.md."""
        tag_slug = slugify(tag)
        tag_dir = self.vault.indices_dir / "tags"
        tag_dir.mkdir(parents=True, exist_ok=True)
        path = tag_dir / f"tag-{tag_slug}.md"

        now = datetime.now(timezone.utc).isoformat()
        metadata = {
            "id": f"tag-{tag_slug}",
            "title": f"Tag: {tag}",
            "type": "tag-page",
            "tag": tag,
            "article_count": len(article_ids),
            "created": now,
            "updated": now,
            "auto_generated": True,
        }

        body_parts: list[str] = [
            f"# Tag: {tag}\n",
            f"> Articles tagged with **{tag}** "
            f"({len(article_ids)} article{'s' if len(article_ids) != 1 else ''}).\n",
            "## Articles\n",
        ]
        for aid in sorted(article_ids):
            body_parts.append(f"- [[{aid}]]")

        body_parts.append(
            f"\n---\n*Auto-generated by OAR Index Builder • "
            f"{len(article_ids)} articles*\n"
        )

        body = "\n".join(body_parts)
        self.fm.write(path, metadata, body)
        return path

    def auto_generate_tags(self) -> list[Path]:
        """Scan all compiled articles, collect tags, generate tag pages.

        Returns list of created/updated tag page paths.
        """
        tag_articles = self.list_tags()
        created: list[Path] = []
        for tag, article_ids in sorted(tag_articles.items()):
            path = self.build_tag_page(tag, article_ids)
            created.append(path)
        return created

    def list_tags(self) -> dict[str, list[str]]:
        """Return {tag_name: [article_ids]} for all tags across compiled articles."""
        tag_map: dict[str, list[str]] = defaultdict(list)
        for path in self.ops.list_compiled_articles():
            meta, _ = self.ops.read_article(path)
            article_id = meta.get("id")
            if not article_id:
                continue
            tags = meta.get("tags", [])
            if isinstance(tags, str):
                tags = [tags]
            for tag in tags:
                tag_map[tag].append(article_id)
        return dict(tag_map)
